### ISSUE TITLE
Computing density_of_x (alternatively "counting number of x)" while re-gridding

### ISSUE THREAD

**Issue by mraspaud** [pytroll/pyresample#10] opened 2014-09-16 21:28 UTC
_From [lavergne...@gmail.com](https://code.google.com/u/110388910077036912843/) on May 06, 2013 08:42:38_

Hi,

This is more a feature request:

I have a fine resolution (1/20 deg) global land/water mask. Each grid cell has thus a lat, lon, and a byte code for "ocean", "land", "lake", etc...

I would like to compute the density_of_ocean, density_of_land, density_of_lake, etc... on a, say, polar EASE grid with 25 km spacing. A good approximation for my density_of_land is the ratio between the number of "land" original grid cells falling into a given "target grid" cell, to the total number of original grid cells falling into that same "target grid" cell.

Does pyresample have such a feature?

An alternative for me would be to first remap (nearest neighbour) the 1/20 deg map to a, say 2.5km EASE grid, with grid cells perfectly aligned with my target (25km) grid. Then I can do the density/counting myself.

But I am interested to hear if pyresample can/could do that out of the box :)

Cheers,
Thomas

_Original issue: http://code.google.com/p/pyresample/issues/detail?id=10_

**Comment by davidh-ssec** [comment] 2017-09-09 17:14
I don't think this is possible with nearest neighbor because the default behavior is to only get 1 nearest neighbor. Even if you got more than 1 neighbor I don't think you could be sure that X number of neighbors all fell within the target grid cell. For non-KDTree based resampling this is more likely since you normally perform some kind of weighted average so you would know exactly how many total input pixels when in to the target cell. However, this would still require keeping track of the individual counts which would require that the input being an integer, preferably no bigger than an 8-bit integer, or performing some kind of histogram calculation with buckets.

I think the easiest way to do this is as you've described with two remap calls. Or maybe given the newer `ll2cr` preparation step for `ewa` resampling this could be done as a separate method to the actual resampling.

**Comment by mraspaud** [comment] 2018-04-23 12:05
@TomLav Is this issue still actual ?

**Comment by pnuu** [comment] 2019-10-08 10:18
We now have `bucket` resampling available that can be used to calculate the fraction of categorical (integer type) values per target area location:
```python
# Here I assume you already have target area definition, data and source coordinates available,
# namely `target_area`, `lons`, `lats` and `data`
import dask.array as da
from pyresample.bucket import BucketResampler
# Adjust to match the data
WATER, LAND = 0, 1
resampler = BucketResampler(target_area, lons, lats)
fractions = resampler.get_fractions(data, categories=[WATER, LAND])
fractions = da.compute(fractions)
```
Now `fractions` is a dictionary where keys represent the categories (here `1` and `2`), and the values are pixel-by-pixel fractions of the values: `frac = <number_of_category_X_source_pixels_in_the_bin> / <all_source_pixels_in_the_bin>`.

Closing, as the issue is old and as far as I see resolved by `bucket` resampling.

**Closed by pnuu** 2019-10-08 10:18 UTC
Labels: Priority-Medium, enhancement, imported
